<script>
import './app.css'

const searchKey = 'a'
/** @type {{ title: string, src: string|undefined, a: HTMLAnchorElement }[]} */
let links = $state([])
let title = $state('')
let src = $state('')
let checked = $state(false)
let ready = $state(false)

function load() {
  const browser = new URL(location.href)
  const file = browser.searchParams.get(searchKey) || links[0]?.src
  if (!file) return
  ;({ title = '404', src = '' } = links.find((i) => i.src === file) || {})
  const active = 'menu-active'
  for (const link of links) {
    link.src === file ? link.a.classList.add(active) : link.a.classList.remove(active)
  }
}

/** @param {any} e */
function clicked(e) {
  const a = e.composedPath()[0].closest('a')
  if (a) {
    const target = new URL(a.href)
    if (target.pathname.startsWith(location.pathname) && target.pathname.endsWith('.md')) {
      e.preventDefault()
      // eslint-disable-next-line svelte/prefer-svelte-reactivity
      const browser = new URL(location.href)
      const file = target.pathname.split(browser.pathname).pop()
      file === links[0].src
        ? browser.searchParams.delete(searchKey)
        : browser.searchParams.set(searchKey, file || '')
      browser.hash = target.hash
      history.pushState({}, '', browser.toString())
      load()
      scrollTo(0, 0)
      checked = false
    }
  }
}

/** @param {any} e */
function init(e) {
  links = Array.from(e.target?.querySelectorAll('a') || []).map((a) => ({
    title: a.text,
    src: new URL(a.href).pathname.split(location.pathname).pop(),
    a
  }))
  load()
  ready = true
}
</script>

<svelte:window onpopstate={load} onclick={clicked} />

<svelte:head>
  <title>{title}</title>
</svelte:head>

<div class="drawer lg:drawer-open">
  <input id="drawer-btn" type="checkbox" bind:checked class="drawer-toggle" />
  <div class="drawer-content flex flex-col items-center justify-start">
    {#if ready}
      <zero-md {src} class="min-h-screen w-full">
        <template data-append>
          <!-- prettier-ignore -->
          <style>
.markdown-body{box-sizing:border-box;padding:45px;}@media(max-width:767px){.markdown-body{padding:15px;}}
          </style>
        </template>
        <!-- prettier-ignore -->
        <script type="text/markdown">
# 404
Page not found!
        </script>
      </zero-md>
    {/if}
    <footer class="flex h-40 w-full flex-col items-center justify-center border-t border-base-300">
      <span class="text-xs">
        generated by [<a class="link font-bold" href="https://github.com/zerodevx/zero-md-docs"
          >zero-md-docs</a
        >]
      </span>
    </footer>
    <label
      for="drawer-btn"
      class="drawer-button btn fixed bottom-10 left-2 flex btn-square items-center justify-center text-lg btn-neutral btn-lg lg:hidden"
    >
      ≡
    </label>
  </div>
  <div class="drawer-side border-r border-base-300">
    <label for="drawer-btn" aria-label="close sidebar" class="drawer-overlay"></label>
    <zero-md src="readme.md" no-shadow onzero-md-rendered={init}>
      <template></template>
    </zero-md>
  </div>
</div>

<style lang="postcss">
@reference './app.css';

:global(.drawer-side .markdown-body) {
  @apply h-full bg-base-200;
}

:global(.drawer-side .markdown-body > ul) {
  @apply menu h-full min-h-screen w-80 bg-base-200 p-4;
}
</style>
